### ISSUE TITLE
High level code review

### ISSUE THREAD

**Issue by xtopolis** [frontendella/gallery#23]
Ella,

Here's some things to revisit/refactor to clean up the codebase. Overall, as we discussed, you'll get better with a lot of this as you practice.  A key thing to keep in mind for future projects:
- plan out the rough structure first (like we did with diagrams)
- keep components simple (so they're easy to reuse, easy to test)
- work on one piece at a time, so you know where things break/change as you add more

CSS/Visual:
- [ ] Clear up any console errors/ warnings: (key prop issue, nested <a><a></a></a> tags)
- [x] CSS: Side bars can, but don't often overlap the main content of a page
- [x] CSS: The ❤️ icon is also the highest level z-index, overlapping the sidebar
- [x] CSS: `width: 120%` on the `.nav-item` list items... doesn't seem like the right approach if you're trying to accomplish spacing/layout
- [x] CSS: `toggelFavorite` item at max-width 800px, has a 60% height/width... which seems weird. I'm not sure if you're trying to cover the card, or center it, or?
![image](https://user-images.githubusercontent.com/1111365/180673767-dea647d9-e072-4b2f-8a28-fca6ff422c60.png)

Javascript:
- [x] There are many unused variables, such as all the arguments in in the Albums, Books, Movies files: https://github.com/frontendella/gallery/blob/master/src/pages/Albums.js  (`category`, `number`, etc are defined as function arguments, but never referenced in the function body, you've hardcoded values instead)
- [x] basically remove unused, or commented out code
- [x] some inconsistent use of ids values.. in `<OneItem ` you have `url` as the key, but later use `id` as the key in the same file / nested components
- [ ] an interesting approach to conditional string concatenation/rendering: https://github.com/frontendella/gallery/blob/331ed7660499775536c8366825c8498e8423f18e/src/components/Navbar/Navbar.js#L15 that could be simplified, revisited

If these items were fixed/cleaned up, we could move on to higher level code review comments: architecture, performance, reuse, testabilityt

**Comment by frontendella** [comment]
Resolved 7/9 issues
